version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    expose:
      - 9200
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.0
    ports:
      - 12201:12201/udp
      - 5044:5044
    environment:
      - xpack.monitoring.elasticsearch.url=http://elasticsearch:9200
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    command: logstash -f /usr/share/logstash/pipeline/ --config.reload.automatic

  commandline:
    image: alpine
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: staging
    links:
      - logstash:logstash
    depends_on:
      - logstash
    command: /bin/sh -c "while true; do echo My Message `date`; sleep 1; done;"

  web:
    image: httpd
    ports:
      - 80:80
    links:
      - logstash
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: httpd.access